# Generated by Django 3.0.7 on 2020-12-29 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_blogpost_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='desc',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='contant',
            name='mobno',
            field=models.CharField(max_length=25),
        ),
    ]
